package com.system.mapper;

import com.system.bean.Filemd;

import java.util.List;

public interface FilemdMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_md
     *
     * @mbg.generated Mon May 11 16:23:20 GMT+08:00 2020
     */
    int deleteByPrimaryKey(String fileid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_md
     *
     * @mbg.generated Mon May 11 16:23:20 GMT+08:00 2020
     */
    int insert(Filemd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_md
     *
     * @mbg.generated Mon May 11 16:23:20 GMT+08:00 2020
     */
    int insertSelective(Filemd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_md
     *
     * @mbg.generated Mon May 11 16:23:20 GMT+08:00 2020
     */
    Filemd selectByPrimaryKey(String fileid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_md
     *
     * @mbg.generated Mon May 11 16:23:20 GMT+08:00 2020
     */
    int updateByPrimaryKeySelective(Filemd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_md
     *
     * @mbg.generated Mon May 11 16:23:20 GMT+08:00 2020
     */
    int updateByPrimaryKey(Filemd record);

    /**
     * 功能描述: 
     * @param: 根据用户id查询信息
     * @return: java.util.List<com.system.bean.Filemd>
     * @auther: wk
     * @date: 2020/5/11 0011 16:35
     */
    List<Filemd> fileList(Long userId);
}