package com.system.mapper;

import com.system.bean.Sysuser;

public interface SysuserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbg.generated Sat May 09 16:06:29 GMT+08:00 2020
     */
    int deleteByPrimaryKey(Long userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbg.generated Sat May 09 16:06:29 GMT+08:00 2020
     */
    int insert(Sysuser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbg.generated Sat May 09 16:06:29 GMT+08:00 2020
     */
    int insertSelective(Sysuser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbg.generated Sat May 09 16:06:29 GMT+08:00 2020
     */
    Sysuser selectByPrimaryKey(Long userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbg.generated Sat May 09 16:06:29 GMT+08:00 2020
     */
    int updateByPrimaryKeySelective(Sysuser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbg.generated Sat May 09 16:06:29 GMT+08:00 2020
     */
    int updateByPrimaryKey(Sysuser record);

    /**
     * 功能描述: 
     * @param: 根据用户名查询信息
     * @return: com.system.bean.Sysuser
     * @auther: wk
     * @date: 2020/5/9 0009 16:25
     */
    Sysuser querySysuser(String loginName);
}